import {useEffect,useState} from 'react';
import {SecretField} from '../../components/SecretField';
import {Select} from '../../components/Field';
import type {CloudRecorder,GeneratedKeyRow} from '../../lib/cloud';
function SavedKey({row,client}:{row:GeneratedKeyRow;client:CloudRecorder}){
 const [version,setVersion]=useState(0);
 return <details className="generated-history-row" onToggle={e=>{if(!e.currentTarget.open)setVersion(n=>n+1)}}><summary><strong>{new Date(row.generated_at).toLocaleString()}</strong><span>{row.network} · {row.id.slice(0,8)}</span><span>Generated only · 5 addresses</span></summary><div className="history-detail"><dl><dt>Private key</dt><dd><SecretField key={'private-'+version} label="Private key" readValue={async()=>(await client.reveal(row)).privateKey}/></dd><dt>WIF (compressed)</dt><dd><SecretField key={'wif-'+version} label="WIF (compressed)" readValue={async()=>(await client.reveal(row)).wifCompressed}/></dd><dt>Public key</dt><dd><code>{row.public_key}</code></dd></dl>{row.addresses.map(a=><div className="address-value" key={a.format}><b>{a.format}</b><code>{a.address}</code></div>)}<p>Balance and transactions were not checked.</p></div></details>;
}
export function GeneratedOnlyHistory({client}:{client:CloudRecorder|null}){
 const [search,setSearch]=useState('');const [address,setAddress]=useState('');
 const [network,setNetwork]=useState('all');const [page,setPage]=useState(1);const [size,setSize]=useState(25);const [refresh,setRefresh]=useState(0);const [total,setTotal]=useState<number|null>(null);const [data,setData]=useState<{rows:GeneratedKeyRow[];hasMore:boolean}>({rows:[],hasMore:false});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let active=true;setTotal(null);if(client)client.totalGeneratedKeys().then(n=>{if(active)setTotal(n)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to count records')});return()=>{active=false}},[client,refresh]);
 useEffect(()=>{let active=true;setData({rows:[],hasMore:false});if(!client)return;setBusy(true);setError('');client.generatedKeyHistory(page,size,network,address).then(result=>{if(active)setData(result)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load records')}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[client,page,size,network,address,refresh]);
 return <section className="history-panel"><div className="section-heading"><div><h2>Generate Only history</h2><p>Records saved without balance or transaction checks.</p><div className="history-total"><strong>{total===null?'—':total.toLocaleString()}</strong><span>Total saved keys · all networks</span></div></div><button className="secondary" disabled={!client||busy} onClick={()=>setRefresh(n=>n+1)}>Refresh</button></div>{!client?<p>Sign in to view your saved keys.</p>:<><form className="history-filters" onSubmit={e=>{e.preventDefault();setAddress(search.trim());setPage(1)}}><label>Network<Select value={network} onChange={e=>{setNetwork(e.target.value);setPage(1)}}><option value="all">All networks</option><option value="mainnet">Mainnet</option><option value="testnet">Testnet</option></Select></label><label>Page size<Select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[10,25,50].map(n=><option key={n} value={n}>{n}</option>)}</Select></label><label className="address-search">Exact address · all five types<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search any Bitcoin address" spellCheck={false}/></label><button type="submit" className="secondary" disabled={busy}>Search</button><button type="button" className="secondary" disabled={busy} onClick={()=>{setSearch('');setAddress('');setPage(1)}}>Clear search</button></form>{error&&<p className="error" role="alert">{error}</p>}{busy?<p role="status">Loading records…</p>:!data.rows.length?<p>No saved keys match these filters.</p>:data.rows.map(row=><SavedKey key={row.id} row={row} client={client}/>)}<div className="history-pager"><span>Page {page} · {data.rows.length} records</span><div><button className="secondary" disabled={busy||page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="secondary" disabled={busy||!data.hasMore} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></>}</section>;
}
