import {useEffect,useRef,useState} from 'react';
import {derive,api,explorer,type Network,type ApiProvider} from '../../lib/bitcoin';
import {parsePrivateKey} from '../../lib/private-key';
import {ProviderSelector} from '../../components/ProviderSelector';
import {SecretField} from '../../components/SecretField';
import {Select} from '../../components/Field';
import {amountSats,prepareTransfer,type TransferDraft} from './transaction';
const btc=(value:bigint)=>(Number(value)/1e8).toFixed(8);
export function Transfer({network,provider,onProviderChange,onBusy}:{network:Network;provider:ApiProvider;onProviderChange:(p:ApiProvider)=>void;onBusy:(busy:boolean)=>void}){
 const [entry,setEntry]=useState('');const key=useRef<Uint8Array|null>(null);const [wallet,setWallet]=useState<ReturnType<typeof derive>|null>(null);const [source,setSource]=useState(0);const [destination,setDestination]=useState('');const [amount,setAmount]=useState('');const [rate,setRate]=useState('5');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [draft,setDraft]=useState<TransferDraft|null>(null);const [confirmed,setConfirmed]=useState(false);const [attempted,setAttempted]=useState(false);const [sent,setSent]=useState(false);const controller=useRef<AbortController|null>(null);const active=useRef(true);const lock=useRef(false);
 useEffect(()=>{active.current=true;return()=>{active.current=false;controller.current?.abort();key.current?.fill(0);onBusy(false)}},[onBusy]);
 useEffect(()=>{setDraft(null);setConfirmed(false);setAttempted(false);setSent(false);if(key.current)setWallet(derive(key.current,network));},[network,provider]);
 function resetDraft(){setDraft(null);setConfirmed(false);setAttempted(false);setSent(false);setError('')}
 function unlock(){try{const parsed=parsePrivateKey(entry);key.current?.fill(0);key.current=parsed;setWallet(derive(parsed,network));setEntry('');resetDraft()}catch(e){setError(e instanceof Error?e.message:'Invalid key')}}
 async function prepare(){if(!key.current||lock.current)return;lock.current=true;setBusy(true);onBusy(true);resetDraft();const c=new AbortController();controller.current=c;try{const result=await prepareTransfer(key.current,source,network,provider,destination,amountSats(amount),Number(rate),AbortSignal.any([c.signal,AbortSignal.timeout(120000)]));if(active.current)setDraft(result)}catch(e){if(active.current)setError(e instanceof Error?e.message:'Unable to prepare transaction')}finally{lock.current=false;if(active.current){setBusy(false);onBusy(false)}}}
 async function broadcast(){if(!draft||!confirmed||attempted||lock.current)return;lock.current=true;setAttempted(true);setBusy(true);onBusy(true);setError('');const c=new AbortController();controller.current=c;try{const response=await fetch(`${api(draft.network,draft.provider)}/tx`,{method:'POST',headers:{'Content-Type':'text/plain'},body:draft.raw,signal:AbortSignal.any([c.signal,AbortSignal.timeout(20000)])});const result=(await response.text()).trim();if(!response.ok)throw new Error(`Broadcast rejected: ${result.slice(0,250)}`);if(result!==draft.txid)throw new Error('Unexpected broadcast response. Check the transaction ID in the explorer.');if(active.current){setSent(true);key.current?.fill(0);key.current=null;}}catch(e){if(active.current)setError(`${e instanceof Error?e.message:'Broadcast failed'}. Check the transaction ID before preparing another transfer; it may have been accepted.`)}finally{lock.current=false;if(active.current){setBusy(false);onBusy(false)}}}
 return <section className="control-panel transfer-panel"><h2>Transfer Bitcoin</h2><p>Signing happens in this browser. Transfer keys are never saved to Supabase. Only public addresses and signed transactions are sent to the provider.</p><div className="controls"><ProviderSelector value={provider} onChange={onProviderChange} disabled={busy}/><SecretField label="Private key · 64 hexadecimal characters" value={entry} onChange={setEntry} disabled={busy} placeholder="Enter private key"/><button className="secondary" disabled={busy||!entry.trim()} onClick={unlock}>Load addresses</button></div>{wallet&&<><div className="transfer-addresses">{wallet.addresses.map((address,i)=><div key={address.format}><strong>{address.format}</strong><code>{address.address}</code></div>)}</div><div className="controls"><label>Spend from<Select value={source} disabled={busy} onChange={e=>{setSource(Number(e.target.value));resetDraft()}}>{wallet.addresses.map((address,i)=><option key={address.format} value={i} disabled={i===4}>{address.format}{i===4?' · view only':''}</option>)}</Select></label><label>Destination address<input value={destination} disabled={busy} autoComplete="off" spellCheck={false} onChange={e=>{setDestination(e.target.value);resetDraft()}}/></label><label>Amount · BTC<input value={amount} inputMode="decimal" disabled={busy} onChange={e=>{setAmount(e.target.value);resetDraft()}}/></label><label>Fee rate · sats/vB<input value={rate} inputMode="decimal" disabled={busy} onChange={e=>{setRate(e.target.value);resetDraft()}}/></label><button className="primary" disabled={busy||!key.current||!destination||!amount} onClick={()=>void prepare()}>{busy?'Working…':'Review transfer'}</button></div><p>Uses confirmed outputs from the selected address. Change returns to that same address. Network: {network}.</p></>}{error&&<p className="error" role="alert">{error}</p>}{draft&&<div className="transfer-review"><h3>{sent?'Transaction broadcast':'Review transaction'}</h3><dl><dt>Network</dt><dd>{draft.network}</dd><dt>From</dt><dd><code>{draft.source}</code></dd><dt>To</dt><dd><code>{draft.destination}</code></dd><dt>Amount</dt><dd>{btc(draft.amount)} BTC</dd><dt>Network fee</dt><dd>{btc(draft.fee)} BTC · {draft.fee.toString()} sats</dd><dt>Total spent</dt><dd>{btc(draft.amount+draft.fee)} BTC</dd><dt>Change</dt><dd>{btc(draft.change)} BTC</dd><dt>Inputs / size</dt><dd>{draft.inputs} / {draft.vsize} vB</dd></dl>{!attempted&&<><label className="transfer-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified the destination, amount, fee and network.</label><button className="primary" disabled={!confirmed||busy} onClick={()=>void broadcast()}>Confirm & transfer {btc(draft.amount)} BTC</button></>}<p>Transaction ID: <a href={`${explorer(draft.network)}/tx/${draft.txid}`} target="_blank" rel="noreferrer">{draft.txid}</a></p>{attempted&&!sent&&<p>Broadcast attempted. Check the explorer before sending again.</p>}</div>}</section>
}
