import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {KeyRound,LogOut,UserRound,ChevronDown} from 'lucide-react';
import {CloudRecorder,cloudConfigured} from '../../lib/cloud';
export function SessionControl({disabled,onConnect,onDisconnect}:{disabled:boolean;onConnect:(recorder:CloudRecorder)=>void;onDisconnect:()=>void}){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [client,setClient]=useState<CloudRecorder|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const dialog=useRef<HTMLDialogElement>(null);const [mobile,setMobile]=useState(()=>matchMedia('(pointer: coarse)').matches&&matchMedia('(max-width: 1023px)').matches);
 useEffect(()=>{const query=matchMedia('(max-width: 1023px) and (pointer: coarse)');const update=()=>setMobile(query.matches);query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);
 useEffect(()=>{if(!client&&!dialog.current?.open)dialog.current?.showModal();else if(client)dialog.current?.close()},[client]);
 async function connect(){setBusy(true);setMessage('');try{const fullEmail=email.trim().includes('@')?email.trim():`${email.trim()}@gmail.com`;const recorder=await CloudRecorder.signIn(fullEmail,password,password);setEmail(fullEmail);setClient(recorder);onConnect(recorder);setPassword('')}catch(e){setMessage(e instanceof Error?e.message:'Sign-in failed')}finally{setBusy(false)}}
 async function logout(){if(!client)return;setBusy(true);try{await client.signOut();setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'Sign-out could not be confirmed. Sign in again.')}finally{setClient(null);onDisconnect();setBusy(false)}}
 return <>{client?<details className="session-menu"><summary aria-label={`Signed in as ${email}`}><UserRound size={17}/><span className="session-label">{email.split('@')[0]}</span><ChevronDown size={13}/></summary><div className="session-popover"><small>Signed in</small><strong>{email}</strong><button className="secondary" disabled={busy||disabled} onClick={()=>void logout()}><LogOut size={16}/> Log out</button></div></details>:<span className="session-pending"><UserRound size={17}/></span>}{createPortal(<dialog ref={dialog} className="signin-dialog" onCancel={e=>e.preventDefault()} aria-labelledby="signin-title"><form onSubmit={e=>{e.preventDefault();void connect()}}><div className="signin-icon"><KeyRound size={24}/></div><h2 id="signin-title">Welcome to Chokbit</h2><p>Sign in to start generating and view your history.</p><label>Email<div className="email-input"><input autoFocus required type="text" inputMode="email" autoComplete="username" autoCapitalize="none" spellCheck={false} value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your username" aria-label="Email or Gmail username" disabled={busy}/>{!email.includes('@')&&<span>@gmail.com</span>}</div></label><label>Password<input type="password" inputMode={mobile?'numeric':'text'} required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/></label><p className="signin-error" role="status">{message}</p><button className="primary" disabled={busy||!cloudConfigured}>{busy?'Signing in…':'Sign in'}</button><p className="signin-note">Your password unlocks encrypted records. It stays in this browser session.</p></form></dialog>,document.body)}</>
}
