import {useEffect,useRef,useState} from 'react';
import {Select} from './Field';
import {SecretField} from './SecretField';
import {type CloudRecorder,type RangePreset} from '../lib/cloud';
export function RangePresets({client,onStart,onEnd,disabled}:{client:CloudRecorder|null;start:string;end:string;onStart:(value:string)=>void;onEnd:(value:string)=>void;disabled:boolean}){
 const [rows,setRows]=useState<RangePreset[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const latest=useRef({onStart,onEnd});latest.current={onStart,onEnd};
 useEffect(()=>{let active=true;setRows([]);setSelected('');setMessage('');latest.current.onStart('');latest.current.onEnd('');setBusy(Boolean(client));if(client)void client.rangePresets().then(data=>{if(!active)return;setRows(data);if(data[0]){setSelected(data[0].id);latest.current.onStart(data[0].start_key);latest.current.onEnd(data[0].end_key)}}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:'Could not load favourites')}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[client]);
 const row=rows.find(r=>r.id===selected);
 return <div className="range-presets"><label>Favourite range<Select value={selected} disabled={disabled||busy||!client} onChange={e=>{const next=rows.find(r=>r.id===e.target.value);if(!next||!client)return;setSelected(next.id);onStart(next.start_key);onEnd(next.end_key);setMessage('');void client.useRange(next.id).catch(e=>setMessage(e instanceof Error?e.message:'Default selection could not be saved'))}}><option value="">Select a favourite</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}{r.target_address?' · '+r.target_address.slice(0,10)+'…':''}</option>)}</Select></label>{row&&<div key={row.id}><SecretField label="Range start" value={row.start_key}/><SecretField label="Range end" value={row.end_key}/><p className="range-target"><span>Target address</span><code>{row.target_address||'Not set — add one in Priv Range List'}</code></p></div>}{busy&&<p role="status">Loading favourites…</p>}{message&&<p className="error" role="alert">{message}</p>}{!client?<p>Sign in to load your favourites.</p>:!busy&&!rows.length?<p>No favourites yet. Add one in Priv Range List.</p>:<p>Manage favourites in Priv Range List. Target address is a reference only; no additional API calls.</p>}</div>;
}
