import {useEffect,useRef,useState} from 'react';
import {Plus,RefreshCw,Pencil,Trash2,Star} from 'lucide-react';
import * as btc from '@scure/btc-signer';
import {SecretField} from '../../components/SecretField';
import {type CloudRecorder,type RangePreset} from '../../lib/cloud';
import {parsePrivateKey} from '../../lib/private-key';

export function PrivRangeList({client,onBusy}:{client:CloudRecorder|null;onBusy:(value:boolean)=>void}){
 const [rows,setRows]=useState<RangePreset[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0);
 const [editing,setEditing]=useState<string|null>(null),[name,setName]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[target,setTarget]=useState(''),[deleting,setDeleting]=useState<string|null>(null);
 const active=useRef(true),lock=useRef(false);
 useEffect(()=>{active.current=true;return()=>{active.current=false;onBusy(false)}},[onBusy]);
 const reset=()=>{setEditing(null);setName('');setStart('');setEnd('');setTarget('');setDeleting(null)};
 useEffect(()=>{let current=true;reset();setRows([]);setMessage('');setBusy(Boolean(client));if(client)void client.rangePresets().then(data=>{if(current)setRows(data)}).catch(e=>{if(current)setMessage(e instanceof Error?e.message:'Unable to load ranges')}).finally(()=>{if(current)setBusy(false)});return()=>{current=false}},[client,refresh]);
 async function save(){if(!client||lock.current)return;lock.current=true;setBusy(true);onBusy(true);setMessage('');try{
  const first=start.trim().toLowerCase(),last=end.trim().toLowerCase(),address=target.trim();parsePrivateKey(first);parsePrivateKey(last);
  if(BigInt('0x'+first)>BigInt('0x'+last))throw new Error('Range start must be at or below range end.');
  if(!name.trim())throw new Error('Enter a favourite name.');
  let valid=false;for(const n of [btc.NETWORK,btc.TEST_NETWORK]){try{btc.Address(n).decode(address);valid=true;break}catch{}}
  if(!valid)throw new Error('Enter a valid Bitcoin target address (mainnet or testnet).');
  const data=await client.saveRange(name.trim(),first,last,address,editing||undefined);if(!data[0])throw new Error('Favourite was not saved.');
  if(active.current){setRows(old=>[data[0],...old.filter(r=>r.id!==data[0].id)]);reset();setMessage('Favourite saved. Available in both generators.')}
 }catch(e){if(active.current)setMessage(e instanceof Error?e.message:'Save failed')}finally{lock.current=false;if(active.current){setBusy(false);onBusy(false)}}}
 async function remove(id:string){if(!client||lock.current)return;lock.current=true;setBusy(true);onBusy(true);try{await client.deleteRange(id);if(active.current){setRows(old=>old.filter(r=>r.id!==id));if(editing===id)reset();setDeleting(null);setMessage('Favourite deleted. Generation history is unchanged.')}}catch(e){if(active.current)setMessage(e instanceof Error?e.message:'Delete failed')}finally{lock.current=false;if(active.current){setBusy(false);onBusy(false)}}}
 return <section className="control-panel range-console"><div className="section-heading"><div><h2><Star size={19}/>Priv Range List</h2><p>Favourite ranges shared by Generator and Generate Only.</p></div><button type="button" className="secondary" disabled={busy||!client} onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={16}/>Refresh</button></div>{!client?<p>Sign in to manage your favourite ranges.</p>:<><form className="range-editor" onSubmit={e=>{e.preventDefault();void save()}}><h3>{editing?'Edit favourite':'Add favourite'}</h3><label>Favourite name<input required maxLength={80} value={name} disabled={busy} onChange={e=>setName(e.target.value)} placeholder="My range"/></label><SecretField key={'start-'+(editing||'new')} label="Range start" value={start} onChange={setStart} disabled={busy}/><SecretField key={'end-'+(editing||'new')} label="Range end" value={end} onChange={setEnd} disabled={busy}/><label>Target Address<input required value={target} maxLength={100} disabled={busy} onChange={e=>setTarget(e.target.value)} autoComplete="off" spellCheck={false} placeholder="Bitcoin address"/></label><p>Target Address is saved with the range as a reference. It does not trigger balance checks or transfers.</p><div className="range-actions"><button type="submit" className="primary" disabled={busy}><Plus size={16}/>{editing?'Save changes':'Add favourite'}</button><button type="button" className="secondary" disabled={busy} onClick={reset}>{editing?'Cancel edit':'Clear form'}</button></div></form><p role="status" className="range-message">{message|| (busy?'Loading…':`${rows.length} favourites`)}</p><div className="range-list">{rows.map(row=><article className="range-list-card" key={row.id}><div className="section-heading"><h3>{row.name}</h3><div className="range-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>{setEditing(row.id);setName(row.name);setStart(row.start_key);setEnd(row.end_key);setTarget(row.target_address);setMessage('');setDeleting(null)}}><Pencil size={16}/>Edit</button><button type="button" className="stop" disabled={busy} onClick={()=>setDeleting(row.id)}><Trash2 size={16}/>Delete</button></div></div><SecretField label="Range start" value={row.start_key}/><SecretField label="Range end" value={row.end_key}/><p className="range-target"><span>Target Address</span><code>{row.target_address||'Not set — edit this favourite to add one'}</code></p>{deleting===row.id&&<div className="range-delete-confirm" role="alert"><p>Delete this favourite? Your generated records will not be deleted.</p><button type="button" className="stop" disabled={busy} onClick={()=>void remove(row.id)}>Confirm delete</button><button type="button" className="secondary" disabled={busy} onClick={()=>setDeleting(null)}>Cancel</button></div>}</article>)}{!busy&&!rows.length&&<p>No favourites yet. Add your first range above.</p>}</div></>}</section>;
}
