import type {GenerationRecord} from './recorder';
const url=import.meta.env.VITE_SUPABASE_URL?.replace(/\/$/,'');
const apiKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
export const cloudConfigured=Boolean(url&&apiKey);
const b64=(bytes:Uint8Array)=>btoa(Array.from(bytes,b=>String.fromCharCode(b)).join(''));
const bytes=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
export type Envelope={version:1;salt:string;iv:string;ciphertext:string;iterations:number};
export async function vaultKey(passphrase:string,salt:Uint8Array){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:salt as BufferSource,iterations:600000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function encryptSecret(record:GenerationRecord,key:CryptoKey,salt:Uint8Array):Promise<Envelope>{const iv=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(record.id)},key,new TextEncoder().encode(JSON.stringify({privateKey:record.privateKey,wifCompressed:record.wifCompressed})));return {version:1,salt:b64(salt),iv:b64(iv),ciphertext:b64(new Uint8Array(ciphertext)),iterations:600000};}
export async function decryptSecret(id:string,envelope:Envelope,key:CryptoKey){if(envelope.version!==1||envelope.iterations!==600000)throw new Error('Unsupported encryption format');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(envelope.iv),additionalData:new TextEncoder().encode(id)},key,bytes(envelope.ciphertext));return JSON.parse(new TextDecoder().decode(plain)) as {privateKey:string;wifCompressed:string};}
type Row={id:string;owner_id:string;generated_at:string;network:GenerationRecord['network'];status:string;public_key:string;addresses:GenerationRecord['addresses'];encrypted_secret:Envelope;has_balance:boolean;has_transactions:boolean};
export class CloudRecorder{
 private expires=0;private access='';private refresh='';private owner='';private key!:CryptoKey;private salt=crypto.getRandomValues(new Uint8Array(16));private passphrase='';
 private async request<T>(path:string,options:RequestInit={},auth=false):Promise<T>{if(auth&&Date.now()>this.expires-60000)await this.refreshSession();const response=await fetch(`${url}${path}`,{...options,headers:{apikey:apiKey,'Content-Type':'application/json',...(auth?{Authorization:`Bearer ${this.access}`} :{}),...options.headers},signal:AbortSignal.timeout(20000)});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.msg||body.message||body.error_description||`Supabase HTTP ${response.status}`)}return response.status===204?undefined as T:await response.json();}
 private session(data:{access_token:string;refresh_token:string;expires_in:number;user:{id:string}}){this.access=data.access_token;this.refresh=data.refresh_token;this.expires=Date.now()+data.expires_in*1000;this.owner=data.user.id;}
 private async refreshSession(){this.session(await this.request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:this.refresh})}));}
 static async signIn(email:string,password:string,passphrase:string){if(!cloudConfigured)throw new Error('Configure Supabase environment variables first.');if(passphrase.length<16)throw new Error('Use a vault passphrase of at least 16 characters.');const recorder=new CloudRecorder();recorder.session(await recorder.request('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})}));recorder.passphrase=passphrase;recorder.key=await vaultKey(passphrase,recorder.salt);return recorder;}
 async save(record:GenerationRecord){const encrypted=await encryptSecret(record,this.key,this.salt);await this.request('/rest/v1/generation_records?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:record.id,owner_id:this.owner,generated_at:record.generatedAt,network:record.network,status:record.status,public_key:record.publicKey,addresses:record.addresses,encrypted_secret:encrypted,has_balance:record.addresses.some(a=>(a.balanceConfirmedSats??0)>0||(a.balanceTotalSats??0)>0),has_transactions:record.addresses.some(a=>(a.txCount??0)>0)})},true);}
 async signOut(){try{await this.request('/auth/v1/logout',{method:'POST'},true)}finally{this.access='';this.refresh='';this.passphrase='';}}
 async exportBatch(series:'rec'|'rec_bl'|'rec_tx',batch:number){const rows:Row[]=[];const offset=(batch-1)*5000;const filter=series==='rec_bl'?'&has_balance=eq.true':series==='rec_tx'?'&has_transactions=eq.true':'';for(let page=0;page<5;page++){const data=await this.request<Row[]>(`/rest/v1/generation_records?select=*&owner_id=eq.${this.owner}${filter}&order=generated_at.asc,id.asc&offset=${offset+page*1000}&limit=1000`,{},true);rows.push(...data);if(data.length<1000)break;}if(!rows.length)throw new Error('No records in this batch.');const keys=new Map<string,CryptoKey>();const output=[];for(const row of rows){const salt=row.encrypted_secret.salt;let key=keys.get(salt);if(!key){key=await vaultKey(this.passphrase,bytes(salt));keys.set(salt,key)}let secret;try{secret=await decryptSecret(row.id,row.encrypted_secret,key)}catch{throw new Error('Vault passphrase cannot decrypt this batch. Use the passphrase used when recording.')}output.push({id:row.id,generatedAt:row.generated_at,network:row.network,status:row.status,publicKey:row.public_key,addresses:row.addresses,...secret});}return JSON.stringify(output,null,2);}
}
