import {useState} from 'react';
import {CloudRecorder,cloudConfigured} from './cloud';
export function CloudPanel({disabled,onConnect,onDisconnect}:{disabled:boolean;onConnect:(recorder:CloudRecorder)=>void;onDisconnect:()=>void}){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [client,setClient]=useState<CloudRecorder|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function connect(){setBusy(true);try{const recorder=await CloudRecorder.signIn(email,password,password);setClient(recorder);onConnect(recorder);setPassword('');setMessage('Signed in. Recording enabled.')}catch(e){setMessage(e instanceof Error?e.message:'Sign-in failed')}finally{setBusy(false)}}
 async function logout(){if(!client)return;setBusy(true);try{await client.signOut()}catch(e){setMessage(e instanceof Error?e.message:'Sign-out failed')}finally{setClient(null);onDisconnect();setBusy(false)}}

 return <section className="control-panel"><h2>Supabase recording</h2>{!cloudConfigured?<p>Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable cloud recording.</p>:!client?<form className="controls" onSubmit={e=>{e.preventDefault();void connect()}}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="primary" disabled={disabled||busy}>Sign in & enable recording</button></form>:<div className="controls"><span className="badge complete">Signed in as {email}</span><button className="secondary" disabled={busy||disabled} onClick={logout}>Sign out</button></div>}<p aria-live="polite">{busy?'Working…':message}</p><p>Private key and WIF are encrypted before upload. Your sign-in password encrypts new records. Keep the original password to decrypt them after a password change.</p></section>
}
