import {useState} from 'react';
import {CloudRecorder,cloudConfigured} from './cloud';
export function CloudPanel({disabled,onConnect,onDisconnect}:{disabled:boolean;onConnect:(recorder:CloudRecorder)=>void;onDisconnect:()=>void}){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [passphrase,setPassphrase]=useState('');const [client,setClient]=useState<CloudRecorder|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [batch,setBatch]=useState(1);const [series,setSeries]=useState<'rec'|'rec_bl'|'rec_tx'>('rec');
 async function connect(){setBusy(true);try{const recorder=await CloudRecorder.signIn(email,password,passphrase);setClient(recorder);onConnect(recorder);setPassword('');setPassphrase('');setMessage('Connected. Vault unlocked for this session.')}catch(e){setMessage(e instanceof Error?e.message:'Sign-in failed')}finally{setBusy(false)}}
 async function logout(){if(!client)return;setBusy(true);try{await client.signOut()}catch(e){setMessage(e instanceof Error?e.message:'Sign-out failed')}finally{setClient(null);onDisconnect();setBusy(false)}}
 async function download(){if(!client)return;setBusy(true);try{const json=await client.exportBatch(series,batch);const blob=URL.createObjectURL(new Blob([json],{type:'application/json'}));const a=document.createElement('a');a.href=blob;a.download=series==='rec'?`rec_${String(batch).padStart(10,'0')}.json`:`${series}_${batch}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(blob),1000);setMessage('JSON exported. Export contains plaintext keys.')}catch(e){setMessage(e instanceof Error?e.message:'Export failed')}finally{setBusy(false)}}
 return <section className="control-panel"><h2>Supabase recording</h2>{!cloudConfigured?<p>Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable cloud recording.</p>:!client?<form className="controls" onSubmit={e=>{e.preventDefault();void connect()}}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><label>Vault passphrase<input type="password" required minLength={16} value={passphrase} onChange={e=>setPassphrase(e.target.value)} autoComplete="off"/></label><button className="primary" disabled={disabled||busy}>Sign in & enable recording</button></form>:<div className="controls"><label>Export records<select value={series} onChange={e=>setSeries(e.target.value as typeof series)}><option value="rec">All keys</option><option value="rec_bl">Positive balance</option><option value="rec_tx">Transactions</option></select></label><label>Batch (5,000 records)<input type="number" min={1} step={1} value={batch} onChange={e=>setBatch(Math.max(1,Math.floor(Number(e.target.value)||1)))}/></label><button className="secondary" disabled={busy||disabled} onClick={download}>Download JSON</button><button className="secondary" disabled={busy||disabled} onClick={logout}>Sign out</button></div>}<p aria-live="polite">{busy?'Working…':message}</p><p>Private key and WIF are encrypted before upload. Keep your vault passphrase; it is required to export keys and cannot be recovered.</p></section>
}
