import React,{useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Bitcoin,Shuffle,Play,Square,Copy,Check,ExternalLink,ShieldCheck,Eye,EyeOff,RefreshCw,ChevronDown,Activity as ActivityIcon,KeyRound} from 'lucide-react';
import {generate,formats,api,explorer,getJSON,sats,type Network,type Activity,type Tx} from './bitcoin';
import './style.css';
type Wallet=ReturnType<typeof generate>;
type Result={activity?:Activity;error?:string;loading?:boolean;checked?:string};
const descriptions=['Legacy · compressed public key','Native SegWit · witness v0','Nested SegWit · P2SH-P2WPKH','Taproot · key-path, BIP341'];
function CopyButton({value}:{value:string}){const [copied,setCopied]=useState(false);return <button className="icon-button" aria-label="Copy to clipboard" onClick={async()=>{try{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{alert('Clipboard unavailable. Select and copy the text manually.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>}</button>}
function App(){
 const [network,setNetwork]=useState<Network>('mainnet');const [wallet,setWallet]=useState<Wallet|null>(null);const [results,setResults]=useState<Result[]>([]);const [busy,setBusy]=useState(false);const [running,setRunning]=useState(false);const [reveal,setReveal]=useState(false);const [interval,setIntervalSeconds]=useState(30);const [count,setCount]=useState(0);const [message,setMessage]=useState('Generate a key to begin.');const [txs,setTxs]=useState<Record<string,Tx[]>>({});const [open,setOpen]=useState<number|null>(null);const [txBusy,setTxBusy]=useState(false);const [txError,setTxError]=useState('');
 const auto=useRef(false);const controller=useRef<AbortController|null>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const txController=useRef<AbortController|null>(null);
 useEffect(()=>()=>{auto.current=false;controller.current?.abort();txController.current?.abort();if(timer.current)clearTimeout(timer.current)},[]);
 function stop(){auto.current=false;setRunning(false);if(timer.current)clearTimeout(timer.current);controller.current?.abort();setBusy(false);setMessage('Stopped. Current key retained.');}
 async function check(w:Wallet,n:Network){
  const c=new AbortController();controller.current=c;setBusy(true);setResults(w.addresses.map(()=>({loading:true})));let activityFound=false;let failed=false;
  for(let i=0;i<4;i++){
   if(c.signal.aborted)break;
   try {const activity=await getJSON<Activity>(`${api(n)}/address/${w.addresses[i].address}`,c.signal);if(activity.chain_stats.tx_count+activity.mempool_stats.tx_count>0)activityFound=true;setResults(old=>old.map((r,j)=>j===i?{activity,checked:new Date().toLocaleTimeString()}:r));}
   catch(e){if(c.signal.aborted)break;failed=true;setResults(old=>old.map((r,j)=>j===i?{error:e instanceof Error?e.message:'Lookup failed'}:r));}
  }
  if(c.signal.aborted){if(controller.current===c)setResults(old=>old.map(r=>r.loading?{error:'Check cancelled'}:r));return;}
  setBusy(false);setMessage(failed?'Some checks failed. Retry to get complete results.':activityFound?'Address activity found. Automatic generation paused.':'All four addresses checked.');
  if(failed||activityFound){auto.current=false;setRunning(false)}
  if(auto.current){setMessage(`Next key in ${interval} seconds.`);timer.current=setTimeout(()=>run(n),interval*1000)}
 }
 async function run(n:Network){try{txController.current?.abort();setTxBusy(false);const w=generate(n);setWallet(w);setCount(c=>c+1);setReveal(false);setTxs({});setOpen(null);setTxError('');await check(w,n)}catch(e){setMessage(e instanceof Error?e.message:'Generation failed');auto.current=false;setRunning(false);setBusy(false)}}
 const confirmed=results.reduce((s,r)=>s+(r.activity?sats(r.activity.chain_stats):0),0);const pending=results.reduce((s,r)=>s+(r.activity?sats(r.activity.mempool_stats):0),0);const txCount=results.reduce((s,r)=>s+(r.activity?r.activity.chain_stats.tx_count+r.activity.mempool_stats.tx_count:0),0);const complete=results.length===4&&results.every(r=>r.activity);
 async function loadTx(i:number,more=false){if(!wallet)return;const address=wallet.addresses[i].address;setOpen(i);setTxBusy(true);setTxError('');const c=new AbortController();txController.current?.abort();txController.current=c;const existing=txs[address]||[];const last=existing.filter(t=>t.status.confirmed).at(-1);try{const data=await getJSON<Tx[]>(`${api(network)}/address/${address}/txs${more&&last?`/chain/${last.txid}`:''}`,c.signal);setTxs(old=>({...old,[address]:more?[...existing,...data.filter(t=>!existing.some(x=>x.txid===t.txid))]:data}));if(more&&!data.length)setTxError('No more confirmed transactions.')}catch(e){if(!c.signal.aborted)setTxError(e instanceof Error?e.message:'Could not load transactions')}finally{if(!c.signal.aborted)setTxBusy(false)}}
 return <div className="app"><header><a className="brand" href="/"><span className="bitcoin-mark"><Bitcoin size={25}/></span><span>Bitcoin <b>Key Lab</b></span></a><div className="header-right"><span className="local"><ShieldCheck size={16}/> Keys stay local</span><span className="network-badge">{network==='mainnet'?'BITCOIN MAINNET':'BITCOIN TESTNET'}</span></div></header>
 <main className="mx-auto"><div className="title-row"><div><div className="eyebrow">KEY GENERATION / ADDRESS EXPLORER</div><h1>One key. Four addresses.</h1><p>Generate securely in your browser. Inspect activity on the Bitcoin network.</p></div><div className="small-mark"><Bitcoin size={42}/></div></div>
 <section className="control-panel"><div className="control-top"><div><h2><Shuffle size={19}/> Generator</h2><p>256-bit randomness · secp256k1</p></div><span className={`mode ${running?'active':''}`}>{running?'AUTO RUNNING':busy?'CHECKING':'READY'}</span></div><div className="controls"><label>Network<select value={network} disabled={busy||running} onChange={e=>{txController.current?.abort();setTxBusy(false);setNetwork(e.target.value as Network);setWallet(null);setResults([]);setOpen(null);setTxs({});setMessage('Network changed. Generate a new key.')}}><option value="mainnet">Mainnet</option><option value="testnet">Testnet</option></select></label><label>Auto interval<select value={interval} disabled={running} onChange={e=>setIntervalSeconds(Number(e.target.value))}><option value={30}>30 seconds</option><option value={60}>60 seconds</option><option value={120}>2 minutes</option></select></label><button className="primary" disabled={busy||running} onClick={()=>run(network)}><Shuffle size={17}/> Generate & check</button><button className={running?'stop':'secondary'} disabled={busy&&!running} onClick={()=>{if(running)stop();else{auto.current=true;setRunning(true);run(network)}}}>{running?<Square size={16}/>:<Play size={16}/>} {running?'Stop auto':'Start auto'}</button></div><div className="status-line" aria-live="polite"><span className={busy?'pulse':''}><ActivityIcon size={15}/>{message}</span><span>{count.toLocaleString()} keys generated this session</span></div></section>
 <div className="stats-grid"><div><span>Confirmed balance</span><strong>{complete?(confirmed/1e8).toFixed(8):'—'}<small> BTC</small></strong><p>{complete?`${confirmed.toLocaleString()} satoshis`:'Awaiting all address checks'}</p></div><div><span>Mempool change</span><strong>{complete?(pending/1e8).toFixed(8):'—'}<small> BTC</small></strong><p>Unconfirmed net balance change</p></div><div><span>Address transaction count</span><strong>{complete?txCount:'—'}<small> TX</small></strong><p>Sum across formats; may overlap</p></div></div>
 <section className="key-panel"><div className="section-heading"><h2><KeyRound size={18}/> Current private key</h2><button className="text-button" disabled={!wallet} onClick={()=>setReveal(!reveal)}>{reveal?<EyeOff size={16}/>:<Eye size={16}/>} {reveal?'Hide key':'Reveal key'}</button></div><div className="key-value"><code>{wallet?(reveal?wallet.key:'•••••••• •••••••• •••••••• •••••••• •••••••• •••••••• •••••••• ••••••••'):'No key generated yet'}</code>{wallet&&reveal&&<CopyButton value={wallet.key}/>}</div>{wallet&&reveal&&<div className="wif"><span>WIF (compressed)</span><code>{wallet.wif}</code><CopyButton value={wallet.wif}/></div>}<p>Memory only. Refreshing clears the key. Never use this experimental app to hold real funds.</p></section>
 <div className="section-heading addresses-heading"><h2>Derived addresses <span className="count-badge">4 formats</span></h2><button className="text-button" disabled={!wallet||busy||running} onClick={()=>wallet&&check(wallet,network)}><RefreshCw size={15} className={busy?'spin':''}/> Recheck balances</button></div>
 <div className="address-grid">{formats.map((f,i)=>{const r=results[i];const address=wallet?.addresses[i].address;return <section className="address-card" key={f}><div className="address-title"><span className="format-icon">{String(i+1).padStart(2,'0')}</span><div><h3>{f}</h3><p>{descriptions[i]}</p></div><span className="prefix">{network==='mainnet'?['1…','bc1q…','3…','bc1p…'][i]:['m/n…','tb1q…','2…','tb1p…'][i]}</span></div><div className="address-value"><code>{address||'Generate a key to derive this address'}</code>{address&&<CopyButton value={address}/>}</div><div className="card-metrics"><div><span>Confirmed / BTC</span><strong>{r?.activity?(sats(r.activity.chain_stats)/1e8).toFixed(8):'—'}</strong></div><div><span>Transactions</span><strong>{r?.activity?r.activity.chain_stats.tx_count+r.activity.mempool_stats.tx_count:'—'}</strong></div></div>{r?.activity&&<div className="pending">Mempool: {sats(r.activity.mempool_stats).toLocaleString()} sats</div>}<div className="card-bottom"><span className={r?.error?'error':''}>{r?.loading?'Checking blockchain…':r?.error|| (r?.checked?`Checked ${r.checked}`:'Not checked')}</span>{address&&<a href={`${explorer(network)}/address/${address}`} target="_blank" rel="noreferrer" aria-label={`Open ${f} in explorer`}><ExternalLink size={15}/></a>}</div><button className="history-button" disabled={!address||busy||running} onClick={()=>open===i?setOpen(null):loadTx(i)}>Transaction history <ChevronDown size={16} style={{transform:open===i?'rotate(180deg)':undefined}}/></button>{open===i&&address&&<div className="tx-list">{txBusy&&<p>Loading transactions…</p>}{txError&&<p className="error">{txError}</p>}{!txBusy&&!txError&&!(txs[address]||[]).length&&<p>No transactions for this address.</p>}{(txs[address]||[]).map(t=><a key={t.txid} href={`${explorer(network)}/tx/${t.txid}`} target="_blank" rel="noreferrer"><code>{t.txid.slice(0,16)}…{t.txid.slice(-8)}</code><span>{t.status.confirmed?`Block ${t.status.block_height}`:'Unconfirmed'} · fee {t.fee} sats</span></a>)}{(txs[address]||[]).filter(t=>t.status.confirmed).length>=25&&<button disabled={txBusy} className="text-button" onClick={()=>loadTx(i,true)}>Load older transactions</button>}</div>}</section>})}</div>
 <footer><div><ShieldCheck size={18}/><p>Private keys never leave this browser. Public address lookups go to Blockstream.</p></div><p>Random generation is not a practical way to discover funded wallets.<br/>P2SH here means nested SegWit. P2TR includes the Taproot tweak.</p></footer></main></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
