import {generate,sats,type Network,type Activity} from './bitcoin';
type FileHandle={getFile():Promise<File>;createWritable():Promise<{write(data:string):Promise<void>;close():Promise<void>}>};
type Directory={getDirectoryHandle(name:string,options:{create:boolean}):Promise<Directory>;getFileHandle(name:string,options?:{create:boolean}):Promise<FileHandle>;values():AsyncIterable<{name:string}>};
export type RecordResult={activity?:Activity;error?:string};
export type GenerationRecord={id:string;generatedAt:string;network:Network;privateKey:string;wifCompressed:string;publicKey:string;status:string;addresses:{format:string;address:string;balanceConfirmedSats:number|null;mempoolChangeSats:number|null;balanceTotalSats:number|null;txCount:number|null;activity:Activity|null;error:string|null}[]};
const limit=5000;
const name=(series:string,index:number)=>series==='rec'?`rec_${String(index).padStart(10,'0')}.json`:`${series}_${index}.json`;
export function makeRecord(wallet:ReturnType<typeof generate>,network:Network):GenerationRecord{return {id:crypto.randomUUID(),generatedAt:new Date().toISOString(),network,privateKey:wallet.key,wifCompressed:wallet.wif,publicKey:wallet.pub,status:'checking',addresses:wallet.addresses.map(a=>({...a,balanceConfirmedSats:null,mempoolChangeSats:null,balanceTotalSats:null,txCount:null,activity:null,error:null}))};}
export function finishRecord(record:GenerationRecord,results:RecordResult[]){record.addresses=record.addresses.map((a,i)=>{const r=results[i];const v=r?.activity;return {...a,balanceConfirmedSats:v?sats(v.chain_stats):null,mempoolChangeSats:v?sats(v.mempool_stats):null,balanceTotalSats:v?sats(v.chain_stats)+sats(v.mempool_stats):null,txCount:v?v.chain_stats.tx_count+v.mempool_stats.tx_count:null,activity:v??null,error:r?.error??(!v?'Check cancelled or incomplete':null)}});record.status=record.addresses.every(a=>a.activity)?'complete':'incomplete';}
export class Recorder{
 private indexes:Record<string,number>={rec:1,rec_bl:1,rec_tx:1};
 private cache=new Map<string,GenerationRecord[]>();
 private locations=new Map<string,Record<string,string>>();
 constructor(private dir:Directory){}
 static async select(){const picker=(window as unknown as {showDirectoryPicker?: (options:{mode:string})=>Promise<Directory>}).showDirectoryPicker;if(!picker)throw new Error('Folder recording requires Chrome or Edge on desktop.');const root=await picker({mode:'readwrite'});const data=await root.getDirectoryHandle('data',{create:true});const dir=await data.getDirectoryHandle('records',{create:true});const recorder=new Recorder(dir);for await(const entry of dir.values()){const match=/^(rec|rec_bl|rec_tx)_(\d+)\.json$/.exec(entry.name);if(match)recorder.indexes[match[1]]=Math.max(recorder.indexes[match[1]],Number(match[2]));}return recorder;}
 private async read(filename:string){if(this.cache.has(filename))return this.cache.get(filename)!;let handle:FileHandle;try{handle=await this.dir.getFileHandle(filename)}catch(e){if(e instanceof DOMException&&e.name==='NotFoundError'){this.cache.set(filename,[]);return []}throw e}const parsed=JSON.parse(await (await handle.getFile()).text());if(!Array.isArray(parsed)||parsed.length>limit||parsed.some(r=>!r||typeof r.id!=='string'||!Array.isArray(r.addresses)))throw new Error(`Invalid recording file: ${filename}`);this.cache.set(filename,parsed);return parsed as GenerationRecord[];}
 private async write(filename:string,records:GenerationRecord[]){const handle=await this.dir.getFileHandle(filename,{create:true});const writable=await handle.createWritable();await writable.write(JSON.stringify(records,null,2)+'\n');await writable.close();this.cache.clear();this.cache.set(filename,records);}
 private async saveSeries(series:string,record:GenerationRecord){const locations=this.locations.get(record.id)??{};let filename=locations[series]??name(series,this.indexes[series]);let records=await this.read(filename);if(!locations[series]&&records.length>=limit){this.indexes[series]++;filename=name(series,this.indexes[series]);records=await this.read(filename)}const index=records.findIndex(r=>r.id===record.id);const next=records.slice();if(index<0)next.push(structuredClone(record));else next[index]=structuredClone(record);await this.write(filename,next);locations[series]=filename;this.locations.set(record.id,locations);}
 async save(record:GenerationRecord){await this.saveSeries('rec',record);const locations=this.locations.get(record.id)!;if(locations.rec_bl||record.addresses.some(a=>(a.balanceConfirmedSats??0)>0||(a.balanceTotalSats??0)>0))await this.saveSeries('rec_bl',record);if(locations.rec_tx||record.addresses.some(a=>(a.txCount??0)>0))await this.saveSeries('rec_tx',record);}
}
